version: '3.8'

services:

  db:
    image: postgres:14.2
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
