### Create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "user": {
    "username": "Ryth",
    "email": "ryth@em.ail",
    "password": "123"
  }
}


### Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "user": {
    "email": "ryth@em.ail",
    "password": "123"
  }
}


### Get user
GET http://localhost:3000/user
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJSeXRoIiwiZW1haWwiOiJyeXRoQGVtLmFpbCIsImlhdCI6MTY1Mjk0NDIyNX0.1Le-vaHeyXzCum4tzzE1DQf71djMNAilGMOJxT1Fw7c


### Update current user
PUT http://localhost:3000/user
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJSeXRoIiwiZW1haWwiOiJyeXRoQGVtLmFpbCIsImlhdCI6MTY1Mjk0NDIyNX0.1Le-vaHeyXzCum4tzzE1DQf71djMNAilGMOJxT1Fw7c
Content-Type: application/json

{
  "user": {
    "bio": "The individual captures awareness which is not private."
  }
}
